name: Build iOS app with Expo EAS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest # Use GitHub's free macOS runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install -g eas-cli
          npm install
        env:
          EXPO_TOKEN: bP6a3RjVWKnW01DB6eJeMMLiVNLfROHEU5t2KpDS

      - name: Authenticate with Expo
        run: eas login --token ${{ EXPO_TOKEN }}

      - name: Run iOS build
        run: eas build --platform ios --profile development --non-interactive
      - name: Cleanup GitHub Runner Cache
        run: sudo rm -rf /usr/local/share/boost /usr/local/Cellar

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: ${{ github.workspace}}
